# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test Plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java8-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: renatoathaydes/setup-java-sdkman@v2.1.0
      with:
        java-version: 8.0.272-zulu
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build

  test-examples:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      id: setup-java8
      uses: renatoathaydes/setup-java-sdkman@v2.1.0
      with:
        java-version: 8.0.272-zulu
    - name: Set up JDK 11 with JavaFX
      uses: renatoathaydes/setup-java-sdkman@v2.0
      with:
        java-version: 11.0.8.fx-zulu
    - name: Set up JDK 11 OpenJDK
      uses: renatoathaydes/setup-java-sdkman@v2.0
      with:
        java-version: 11.0.2-open
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Use Java 8 to build this plugin
      run: "${{ steps.setup-java8.outputs.sdkCommand }} use java 8.0.272-zulu"
    - name: Build
      run: ./gradlew build
    - name: Test Examples
      run: ./gradlew testExamples
